#!/usr/bin/env python

Import("env")
Import("env_modules")

module_env = env.Clone()

module_env.add_source_files(env.modules_sources, "*.cpp")
module_env.add_source_files(env.modules_sources, "blackboard/*.cpp")
module_env.add_source_files(env.modules_sources, "blackboard/bb_param/*.cpp")
module_env.add_source_files(env.modules_sources, "bt/*.cpp")
module_env.add_source_files(env.modules_sources, "bt/tasks/*.cpp")
module_env.add_source_files(env.modules_sources, "bt/tasks/composites/*.cpp")
module_env.add_source_files(env.modules_sources, "bt/tasks/actions/*.cpp")
module_env.add_source_files(env.modules_sources, "bt/tasks/decorators/*.cpp")
module_env.add_source_files(env.modules_sources, "bt/tasks/conditions/*.cpp")
if env.editor_build:
    module_env.add_source_files(env.modules_sources, "editor/*.cpp")
module_env.add_source_files(env.modules_sources, "editor/debugger/*.cpp")
module_env.add_source_files(env.modules_sources, "hsm/*.cpp")
module_env.add_source_files(env.modules_sources, "util/*.cpp")
