#!/usr/bin/env python

Import("env")
Import("env_modules")

module_env = env.Clone()

module_env.add_source_files(env.modules_sources, "*.cpp")
module_env.add_source_files(env.modules_sources, "bt/*.cpp")
module_env.add_source_files(env.modules_sources, "bt/composites/*.cpp")
module_env.add_source_files(env.modules_sources, "bt/actions/*.cpp")
module_env.add_source_files(env.modules_sources, "bt/decorators/*.cpp")
module_env.add_source_files(env.modules_sources, "bt/conditions/*.cpp")
module_env.add_source_files(env.modules_sources, "bb_param/*.cpp")
module_env.add_source_files(env.modules_sources, "debugger/*.cpp")
if env.editor_build:
    module_env.add_source_files(env.modules_sources, "editor/*.cpp")
