#!/usr/bin/env python
"""
doc_data_generator.py
==============================================================================
Copyright (c) 2023-present Serhii Snitsaruk and the LimboAI contributors.

Use of this source code is governed by an MIT-style
license that can be found in the LICENSE file or at
https://opensource.org/licenses/MIT.
==============================================================================

Post-processes the generated doc_data.gen.cpp to inject an accessor function
for LimboDocData. This allows GDExtension builds to access the compressed XML
documentation data without duplicating it.
"""

ACCESSOR_CODE = """
// Accessor function for LimboDocData to retrieve compressed documentation.
// This avoids duplicating the documentation data in a separate file.
void limbo_doc_data_load(const unsigned char **r_data, int *r_compressed_size, int *r_uncompressed_size) {
\t*r_data = _doc_data_compressed;
\t*r_compressed_size = _doc_data_compressed_size;
\t*r_uncompressed_size = _doc_data_uncompressed_size;
}
"""


def inject_doc_data_accessor(target, source, env):
    """
    SCons post-action that post-processes doc_data.gen.cpp to inject
    an accessor function for LimboDocData.

    The target is the doc_data.gen.cpp file generated by GodotCPPDocData.
    We read it, check if the accessor already exists, and append it if not.
    """
    filepath = str(target[0])

    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()

    # Check if accessor already exists
    if "limbo_doc_data_load" in content:
        print(f"Accessor already present in {filepath}")
        return

    # Append the accessor function
    with open(filepath, "a", encoding="utf-8") as f:
        f.write(ACCESSOR_CODE)

    print(f"Injected doc data accessor into {filepath}")


def inject_accessor_from_cli(filepath):
    """
    Command-line function to inject the accessor into a doc_data.gen.cpp file.
    """
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()

    if "limbo_doc_data_load" in content:
        print(f"Accessor already present in {filepath}")
        return

    with open(filepath, "a", encoding="utf-8") as f:
        f.write(ACCESSOR_CODE)

    print(f"Injected doc data accessor into {filepath}")


if __name__ == "__main__":
    import sys

    if len(sys.argv) < 2:
        print("Usage: doc_data_generator.py <doc_data.gen.cpp>")
        print("Example: doc_data_generator.py gen/doc_data.gen.cpp")
        sys.exit(1)

    inject_accessor_from_cli(sys.argv[1])
