name: Setup Linux toolchain

inputs:
  arch:
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up environment
      shell: bash
      run: |
        # ! Settings:
        TOOLCHAIN_64_URL=https://github.com/godotengine/buildroot/releases/download/godot-2023.08.x-4/x86_64-godot-linux-gnu_sdk-buildroot.tar.bz2
        TOOLCHAIN_64_SHA=b534305ef71487014c47e0f5fa146f411ff3b2bf
        TOOLCHAIN_32_URL=https://github.com/godotengine/buildroot/releases/download/godot-2023.08.x-4/i686-godot-linux-gnu_sdk-buildroot.tar.bz2
        TOOLCHAIN_32_SHA=d4177d80c82e8e9a4ac13155b4369cf1695a726a
        TOOLCHAIN_ARM64_URL=https://github.com/godotengine/buildroot/releases/download/godot-2023.08.x-4/aarch64-godot-linux-gnu_sdk-buildroot.tar.bz2
        TOOLCHAIN_ARM64_SHA=ccb38161202052c368a7abf35c84214f66c4f721
        TOOLCHAIN_ARM32_URL=https://github.com/godotengine/buildroot/releases/download/godot-2023.08.x-4/arm-godot-linux-gnueabihf_sdk-buildroot.tar.bz2
        TOOLCHAIN_ARM32_SHA=9b09667e24cce8a121144b2feb59cf03105e33dd

        # ! Export variables:
        if [[ "${{ inputs.arch }}" == "x86_64" ]]; then
          echo "TOOLCHAIN_URL=${TOOLCHAIN_64_URL}" >> "$GITHUB_ENV"
          echo "TOOLCHAIN_SHA=${TOOLCHAIN_64_SHA}" >> "$GITHUB_ENV"
        elif [[ "${{ inputs.arch }}" == "x86_32" ]]; then
          echo "TOOLCHAIN_URL=${TOOLCHAIN_32_URL}" >> "$GITHUB_ENV"
          echo "TOOLCHAIN_SHA=${TOOLCHAIN_32_SHA}" >> "$GITHUB_ENV"
        elif [[ "${{ inputs.arch }}" == "arm64" ]]; then
          echo "TOOLCHAIN_URL=${TOOLCHAIN_ARM64_URL}" >> "$GITHUB_ENV"
          echo "TOOLCHAIN_SHA=${TOOLCHAIN_ARM64_SHA}" >> "$GITHUB_ENV"
        elif [[ "${{ inputs.arch }}" == "arm32" ]]; then
          echo "TOOLCHAIN_URL=${TOOLCHAIN_ARM32_URL}" >> "$GITHUB_ENV"
          echo "TOOLCHAIN_SHA=${TOOLCHAIN_ARM32_SHA}" >> "$GITHUB_ENV"
        fi

    - name: Cache buildroot
      id: cache-buildroot
      uses: actions/cache@v4
      with:
        path: buildroot
        key: ${{env.TOOLCHAIN_SHA}}

    - name: Set up buildroot
      if: steps.cache-buildroot.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mkdir buildroot
        wget ${TOOLCHAIN_URL} -O buildroot/buildroot.tar.bz2
        cd buildroot
        echo "${TOOLCHAIN_SHA}  buildroot.tar.bz2"
        echo "${TOOLCHAIN_SHA}  buildroot.tar.bz2" | shasum --check
        tar -xjf buildroot.tar.bz2 --strip-components=1
        ls -l
        rm buildroot.tar.bz2
        ./relocate-sdk.sh
        cd ..
