name: 📦️ Merge templates
on:
  workflow_call:
    inputs:
      godot-ref:
        description: A tag, branch or commit hash in the Godot repository.
        type: string

  workflow_dispatch:
    inputs:
      godot-ref:
        description: A tag, branch or commit hash in the Godot repository.
        type: string

jobs:
  merge-templates:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Godot
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          repository: godotengine/godot
          ref: ${{ inputs.godot-ref }}

      - name: Clone LimboAI module
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          path: modules/limboai

      # Init version environment variables.
      - uses: ./modules/limboai/.github/actions/init-version

      - name: Merge classical templates
        uses: actions/upload-artifact/merge@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{env.NAME_PREFIX}}.export-templates
          pattern: ${{env.NAME_PREFIX}}.{export-templates,template_}*
          delete-merged: true

      - name: Merge .NET templates
        uses: actions/upload-artifact/merge@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{env.NAME_PREFIX}}.dotnet.export-templates
          pattern: ${{env.NAME_PREFIX}}.dotnet.{export-templates,template_}*
          delete-merged: true
